import pcImage from "@/assets/images/test/products/pc.png";
import headphonesImage from "@/assets/images/test/products/headphones.webp";

export const productsDb = [
  {
    id: 1,
    subcategoryId: 1,
    name: "Test 1",
    title: "",
    slug: "test1",
    price: 123.41,
    currency: "$",
    summary: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    description: "",
    discount: 0,
    onSale: false,
    salePrice: 0,
    unitsInStock: 10,
    unitsSold: 0,
    rating: 0,
    ratingCount: 0,
    img: pcImage,
  },
  {
    id: 2,
    subcategoryId: 1,
    name: "Test 2",
    title: "",
    slug: "test2",
    price: 123.42,
    currency: "$",
    summary: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    description: "",
    discount: 0,
    onSale: false,
    salePrice: 0,
    unitsInStock: 10,
    unitsSold: 0,
    rating: 0,
    ratingCount: 0,
    img: headphonesImage,
  },
  {
    id: 3,
    subcategoryId: 1,
    name: "Test 3",
    title: "",
    slug: "test3",
    price: 123.43,
    currency: "$",
    summary: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    description: "",
    discount: 0,
    onSale: false,
    salePrice: 0,
    unitsInStock: 10,
    unitsSold: 0,
    rating: 0,
    ratingCount: 0,
    img: pcImage,
  },
  {
    id: 4,
    subcategoryId: 1,
    name: "Test 4",
    title: "",
    slug: "test4",
    price: 123.44,
    currency: "$",
    summary: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    description: "",
    discount: 0,
    onSale: false,
    salePrice: 0,
    unitsInStock: 10,
    unitsSold: 0,
    rating: 0,
    ratingCount: 0,
    img: headphonesImage,
  },
  {
    id: 5,
    subcategoryId: 1,
    name: "Test 5",
    title: "",
    slug: "test5",
    price: 123.45,
    currency: "$",
    summary: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    description: "",
    discount: 0,
    onSale: false,
    salePrice: 0,
    unitsInStock: 10,
    unitsSold: 0,
    rating: 0,
    ratingCount: 0,
    img: pcImage,
  },
  {
    id: 6,
    subcategoryId: 1,
    name: "Test 6",
    title: "",
    slug: "test6",
    price: 123.46,
    currency: "$",
    summary: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    description: "",
    discount: 0,
    onSale: false,
    salePrice: 0,
    unitsInStock: 10,
    unitsSold: 0,
    rating: 0,
    ratingCount: 0,
    img: headphonesImage,
  },
  {
    id: 7,
    subcategoryId: 1,
    name: "Test 7",
    title: "",
    slug: "test7",
    price: 123.47,
    currency: "$",
    summary: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    description: "",
    discount: 0,
    onSale: false,
    salePrice: 0,
    unitsInStock: 10,
    unitsSold: 0,
    rating: 0,
    ratingCount: 0,
    img: pcImage,
  },
  {
    id: 8,
    subcategoryId: 1,
    name: "Test 8",
    title: "",
    slug: "test8",
    price: 123.48,
    currency: "$",
    summary: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    description: "",
    discount: 0,
    onSale: false,
    salePrice: 0,
    unitsInStock: 10,
    unitsSold: 0,
    rating: 0,
    ratingCount: 0,
    img: headphonesImage,
  },
  {
    id: 9,
    subcategoryId: 2,
    name: "Test 9",
    title: "",
    slug: "test9",
    price: 123.41,
    currency: "$",
    summary: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    description: "",
    discount: 0,
    onSale: false,
    salePrice: 0,
    unitsInStock: 10,
    unitsSold: 0,
    rating: 0,
    ratingCount: 0,
    img: pcImage,
  },
  {
    id: 10,
    subcategoryId: 2,
    name: "Test 10",
    title: "",
    slug: "test10",
    price: 123.42,
    currency: "$",
    summary: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    description: "",
    discount: 0,
    onSale: false,
    salePrice: 0,
    unitsInStock: 10,
    unitsSold: 0,
    rating: 0,
    ratingCount: 0,
    img: headphonesImage,
  },
  {
    id: 11,
    subcategoryId: 3,
    name: "Test 11",
    title: "",
    slug: "test11",
    price: 123.43,
    currency: "$",
    summary: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    description: "",
    discount: 0,
    onSale: false,
    salePrice: 0,
    unitsInStock: 10,
    unitsSold: 0,
    rating: 0,
    ratingCount: 0,
    img: pcImage,
  },
  {
    id: 12,
    subcategoryId: 3,
    name: "Test 12",
    title: "",
    slug: "test12",
    price: 123.44,
    currency: "$",
    summary: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    description: "",
    discount: 0,
    onSale: false,
    salePrice: 0,
    unitsInStock: 10,
    unitsSold: 0,
    rating: 0,
    ratingCount: 0,
    img: headphonesImage,
  },
  {
    id: 13,
    subcategoryId: 3,
    name: "Test 13",
    title: "",
    slug: "test13",
    price: 123.45,
    currency: "$",
    summary: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    description: "",
    discount: 0,
    onSale: false,
    salePrice: 0,
    unitsInStock: 10,
    unitsSold: 0,
    rating: 0,
    ratingCount: 0,
    img: pcImage,
  },
  {
    id: 14,
    subcategoryId: 3,
    name: "Test 14",
    title: "",
    slug: "test14",
    price: 123.46,
    currency: "$",
    summary: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    description: "",
    discount: 0,
    onSale: false,
    salePrice: 0,
    unitsInStock: 10,
    unitsSold: 0,
    rating: 0,
    ratingCount: 0,
    img: headphonesImage,
  },
  {
    id: 15,
    subcategoryId: 4,
    name: "Test 15",
    title: "",
    slug: "test15",
    price: 123.47,
    currency: "$",
    summary: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    description: "",
    discount: 0,
    onSale: false,
    salePrice: 0,
    unitsInStock: 10,
    unitsSold: 0,
    rating: 0,
    ratingCount: 0,
    img: pcImage,
  },
  {
    id: 16,
    subcategoryId: 4,
    name: "Test 16",
    title: "",
    slug: "test16",
    price: 123.48,
    currency: "$",
    summary: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    description: "",
    discount: 0,
    onSale: false,
    salePrice: 0,
    unitsInStock: 10,
    unitsSold: 0,
    rating: 0,
    ratingCount: 0,
    img: headphonesImage,
  },
];
