import pcImage from "@/assets/images/test/products/pc.png";
import headphonesImage from "@/assets/images/test/products/headphones.webp";

export const productsDb = [
  {
    id: 1,
    subcategoryId: 1,
    name: "Test 1",
    title:
      "Acer Predator Helios 300, 15.6' FHD IPS, Intel i7 8750H, NVidia GeForce 1060 4GB, 16GB RAM DDR4, 512GB SSD",
    slug: "test1",
    price: 123.41,
    currency: "$",
    summary: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    description:
      "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Aliquam eveniet iure sunt quo necessitatibus, aperiam repellendus ut veniam magnam nisi. Suscipit, sequi. Incidunt alias minus eaque dolor quia eius unde eum fuga quas corrupti ipsa assumenda quae deleniti excepturi recusandae repellendus et quibusdam quidem, rem consequuntur odio. Tempore, omnis quo.",
    discount: 0,
    onSale: false,
    salePrice: 0,
    unitsInStock: 10,
    unitsSold: 0,
    rating: 3.4,
    ratingCount: 1,
    img: pcImage,
  },
  {
    id: 2,
    subcategoryId: 1,
    name: "Test 2",
    title:
      "Acer Predator Helios 300, 15.6' FHD IPS, Intel i7 8750H, NVidia GeForce 1060 4GB, 16GB RAM DDR4, 512GB SSD",
    slug: "test2",
    price: 123.42,
    currency: "$",
    summary: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    description: "",
    discount: 0,
    onSale: false,
    salePrice: 0,
    unitsInStock: 10,
    unitsSold: 0,
    rating: 2.5,
    ratingCount: 0,
    img: headphonesImage,
  },
  {
    id: 3,
    subcategoryId: 1,
    name: "Test 3",
    title:
      "Acer Predator Helios 300, 15.6' FHD IPS, Intel i7 8750H, NVidia GeForce 1060 4GB, 16GB RAM DDR4, 512GB SSD",
    slug: "test3",
    price: 223.43,
    currency: "$",
    summary: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    description: "",
    discount: 0,
    onSale: false,
    salePrice: 0,
    unitsInStock: 10,
    unitsSold: 0,
    rating: 2.6,
    ratingCount: 0,
    img: pcImage,
  },
  {
    id: 4,
    subcategoryId: 1,
    name: "Test 4",
    title:
      "Acer Predator Helios 300, 15.6' FHD IPS, Intel i7 8750H, NVidia GeForce 1060 4GB, 16GB RAM DDR4, 512GB SSD",
    slug: "test4",
    price: 123.44,
    currency: "$",
    summary: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    description: "",
    discount: 0,
    onSale: false,
    salePrice: 0,
    unitsInStock: 10,
    unitsSold: 0,
    rating: 4.5,
    ratingCount: 0,
    img: headphonesImage,
  },
  {
    id: 5,
    subcategoryId: 1,
    name: "Test 5",
    title:
      "Acer Predator Helios 300, 15.6' FHD IPS, Intel i7 8750H, NVidia GeForce 1060 4GB, 16GB RAM DDR4, 512GB SSD",
    slug: "test5",
    price: 123.45,
    currency: "$",
    summary: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    description: "",
    discount: 0,
    onSale: false,
    salePrice: 0,
    unitsInStock: 10,
    unitsSold: 0,
    rating: 5,
    ratingCount: 0,
    img: pcImage,
  },
  {
    id: 6,
    subcategoryId: 1,
    name: "Test 6",
    title:
      "Acer Predator Helios 300, 15.6' FHD IPS, Intel i7 8750H, NVidia GeForce 1060 4GB, 16GB RAM DDR4, 512GB SSD",
    slug: "test6",
    price: 123.46,
    currency: "$",
    summary: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    description: "",
    discount: 0,
    onSale: false,
    salePrice: 0,
    unitsInStock: 10,
    unitsSold: 0,
    rating: 0,
    ratingCount: 0,
    img: headphonesImage,
  },
  {
    id: 7,
    subcategoryId: 1,
    name: "Test 7",
    title:
      "Acer Predator Helios 300, 15.6' FHD IPS, Intel i7 8750H, NVidia GeForce 1060 4GB, 16GB RAM DDR4, 512GB SSD",
    slug: "test7",
    price: 123.47,
    currency: "$",
    summary: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    description: "",
    discount: 0,
    onSale: false,
    salePrice: 0,
    unitsInStock: 10,
    unitsSold: 0,
    rating: 0,
    ratingCount: 0,
    img: pcImage,
  },
  {
    id: 8,
    subcategoryId: 1,
    name: "Test 8",
    title:
      "Acer Predator Helios 300, 15.6' FHD IPS, Intel i7 8750H, NVidia GeForce 1060 4GB, 16GB RAM DDR4, 512GB SSD",
    slug: "test8",
    price: 123.48,
    currency: "$",
    summary: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    description: "",
    discount: 0,
    onSale: false,
    salePrice: 0,
    unitsInStock: 10,
    unitsSold: 0,
    rating: 0,
    ratingCount: 0,
    img: headphonesImage,
  },
  {
    id: 9,
    subcategoryId: 2,
    name: "Test 9",
    title:
      "Acer Predator Helios 300, 15.6' FHD IPS, Intel i7 8750H, NVidia GeForce 1060 4GB, 16GB RAM DDR4, 512GB SSD",
    slug: "test9",
    price: 123.41,
    currency: "$",
    summary: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    description: "",
    discount: 0,
    onSale: false,
    salePrice: 0,
    unitsInStock: 10,
    unitsSold: 0,
    rating: 0,
    ratingCount: 0,
    img: pcImage,
  },
  {
    id: 10,
    subcategoryId: 2,
    name: "Test 10",
    title:
      "Acer Predator Helios 300, 15.6' FHD IPS, Intel i7 8750H, NVidia GeForce 1060 4GB, 16GB RAM DDR4, 512GB SSD",
    slug: "test10",
    price: 123.42,
    currency: "$",
    summary: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    description: "",
    discount: 0,
    onSale: false,
    salePrice: 0,
    unitsInStock: 10,
    unitsSold: 0,
    rating: 0,
    ratingCount: 0,
    img: headphonesImage,
  },
  {
    id: 11,
    subcategoryId: 3,
    name: "Test 11",
    title:
      "Acer Predator Helios 300, 15.6' FHD IPS, Intel i7 8750H, NVidia GeForce 1060 4GB, 16GB RAM DDR4, 512GB SSD",
    slug: "test11",
    price: 123.43,
    currency: "$",
    summary: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    description: "",
    discount: 0,
    onSale: false,
    salePrice: 0,
    unitsInStock: 10,
    unitsSold: 0,
    rating: 0,
    ratingCount: 0,
    img: pcImage,
  },
  {
    id: 12,
    subcategoryId: 3,
    name: "Test 12",
    title:
      "Acer Predator Helios 300, 15.6' FHD IPS, Intel i7 8750H, NVidia GeForce 1060 4GB, 16GB RAM DDR4, 512GB SSD",
    slug: "test12",
    price: 123.44,
    currency: "$",
    summary: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    description: "",
    discount: 0,
    onSale: false,
    salePrice: 0,
    unitsInStock: 10,
    unitsSold: 0,
    rating: 0,
    ratingCount: 0,
    img: headphonesImage,
  },
  {
    id: 13,
    subcategoryId: 3,
    name: "Test 13",
    title:
      "Acer Predator Helios 300, 15.6' FHD IPS, Intel i7 8750H, NVidia GeForce 1060 4GB, 16GB RAM DDR4, 512GB SSD",
    slug: "test13",
    price: 123.45,
    currency: "$",
    summary: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    description: "",
    discount: 0,
    onSale: false,
    salePrice: 0,
    unitsInStock: 10,
    unitsSold: 0,
    rating: 0,
    ratingCount: 0,
    img: pcImage,
  },
  {
    id: 14,
    subcategoryId: 3,
    name: "Test 14",
    title:
      "Acer Predator Helios 300, 15.6' FHD IPS, Intel i7 8750H, NVidia GeForce 1060 4GB, 16GB RAM DDR4, 512GB SSD",
    slug: "test14",
    price: 123.46,
    currency: "$",
    summary: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    description: "",
    discount: 0,
    onSale: false,
    salePrice: 0,
    unitsInStock: 10,
    unitsSold: 0,
    rating: 0,
    ratingCount: 0,
    img: headphonesImage,
  },
  {
    id: 15,
    subcategoryId: 4,
    name: "Test 15",
    title:
      "Acer Predator Helios 300, 15.6' FHD IPS, Intel i7 8750H, NVidia GeForce 1060 4GB, 16GB RAM DDR4, 512GB SSD",
    slug: "test15",
    price: 123.47,
    currency: "$",
    summary: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    description: "",
    discount: 0,
    onSale: false,
    salePrice: 0,
    unitsInStock: 10,
    unitsSold: 0,
    rating: 0,
    ratingCount: 0,
    img: pcImage,
  },
  {
    id: 16,
    subcategoryId: 4,
    name: "Test 16",
    title:
      "Acer Predator Helios 300, 15.6' FHD IPS, Intel i7 8750H, NVidia GeForce 1060 4GB, 16GB RAM DDR4, 512GB SSD",
    slug: "test16",
    price: 123.48,
    currency: "$",
    summary: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    description: "",
    discount: 0,
    onSale: false,
    salePrice: 0,
    unitsInStock: 10,
    unitsSold: 0,
    rating: 0,
    ratingCount: 0,
    img: headphonesImage,
  },
];
