FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src

COPY ["./src/TechStore.API/TechStore.API.csproj", "src/TechStore.API/"]
COPY ["./src/TechStore.Application/TechStore.Application.csproj", "src/TechStore.Application/"]
COPY ["./src/TechStore.Domain/TechStore.Domain.csproj", "src/TechStore.Domain/"]
COPY ["./src/TechStore.Infrastructure/TechStore.Infrastructure.csproj", "src/TechStore.Infrastructure/"]
RUN dotnet restore "src/TechStore.API/TechStore.API.csproj"
COPY . .

WORKDIR "/src/src/TechStore.API/"
RUN dotnet build "TechStore.API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "TechStore.API.csproj" -c Release -o /app/publish

FROM base AS runtime
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "TechStore.API.dll"]